import mongoose from 'mongoose'

const itemSchema = new mongoose.Schema({
  _id: mongoose.Schema.Types.ObjectId,
  index: Number,
  product_name_nb: String,
  quantity: String,
  serving_size: String,
  packaging: [String],
  packaging_tags: [String],
  brands: [String],
  brands_tags: [String],
  categories: [String],
  categories_tags: [String],
  labels: [String],
  labels_tags: [String],
  countries: [String],
  countries_tags: [String],
  stores: [String],
  stores_tags: [String],
  manufacturing_places: [String],
  manufacturing_places_tags: [String],
  ingredients_text_nb: [String],
  allergens: [String],
  allergens_tags: [String],
  traces: [String],
  traces_tags: [String],
  nutrition_data_per: String,
  nutrition_data_prepared_per: String,
  energy_kj_value: Number,
  energy_kj_unit: String,
  energy_kcal_value: Number,
  energy_kcal_unit: String,
  fat_value: Number,
  fat_unit: String,
  saturated_fat_value: Number,
  saturated_fat_unit: String,
  carbohydrates_value: Number,
  carbohydrates_unit: String,
  sugars_value: Number,
  sugars_unit: String,
  fiber_value: Number,
  fiber_unit: String,
  proteins_value: Number,
  proteins_unit: String,
  salt_value: Number,
  salt_unit: String,
  sodium_value: Number,
  sodium_unit: String,
  energy_value: Number,
  energy_unit: String,
  monounsaturated_fat_value: String,
  monounsaturated_fat_unit: String,
  polyunsaturated_fat_value: String,
  polyunsaturated_fat_unit: String,
  food_groups: String,
  food_groups_tags: [String],
  nova_groups: Number,
  nova_groups_tags: String,
  nutriscore_grade: String,
  nutriscore_score: Number,
  ecoscore_grade: String,
  ecoscore_score: Number,
  ecoscore_data: {
    missing_key_data: Number,
    agribalyse: {
      code: String,
    },
    adjustments: {
      origins_of_ingredients: {
        value: Number,
      },
      packaging: {
        value: Number,
        non_recyclable_and_non_biodegradable_materials: Number,
      },
      production_system: {
        value: Number,
      },
    },
  },
  data_sources: [String],
})

// Create the "Items" model
const Item = mongoose.model('Item', itemSchema)

export { Item }
